contacts/urls.py
from django.urls import path, include
from .views import (ContactListView, ContactDetailView, 
                    ContactCreateView, ContactUpdateView,
                    ContactDeleteView, PersonContactViewset)
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'contacts', PersonContactViewset)

#view_name='contacts:personcontact-detail'

app_name = 'contacts'
urlpatterns = [
    path('', ContactListView.as_view(), name='index'),
    path('contact/<int:pk>', ContactDetailView.as_view(), name='contact'),
    path('create/', ContactCreateView.as_view(), name='create'),
    path('contact/<int:pk>/update', ContactUpdateView.as_view(), name='contact-update'),
    path('contact/<int:pk>/delete', ContactDeleteView.as_view(), name='contact-delete'),
    path('api/', include(router.urls)),
]

phonebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
]

contacts/models.py
from django.db import models
from django.urls import reverse

class PersonContact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.PositiveBigIntegerField()
    email = models.EmailField()
    date_of_birth = models.DateField()

    class Meta:
        ordering = ['first_name']

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'
    
    def get_absolute_url(self):
        return reverse("contacts:contact", kwargs={"pk": self.pk})
    

contacts/forms.py
from django.forms import ModelForm, TextInput, DateInput, NumberInput, EmailInput
from .models import PersonContact


class PersonContactForm(ModelForm):
    class Meta:
        model = PersonContact
        fields = '__all__'

        widgets = {
            'first_name': TextInput(attrs={'class':'gg'}),
            'first_name': TextInput(attrs={'class':'gg'}),
            'phone_number': NumberInput(attrs={'class': 'gg'}),
            'email': EmailInput(attrs={'class': 'gg'}),
            'date_of_birth': DateInput(attrs={'class': 'gg', 'type':'date'})

        }

contacts/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import PersonContact
from django.urls import reverse_lazy


# api import

from rest_framework import viewsets
from .serializers import PersonContactSerializer

class PersonContactViewset(viewsets.ModelViewSet):
    queryset = PersonContact.objects.all()
    serializer_class = PersonContactSerializer
    

class ContactListView(ListView):
    model = PersonContact
    context_object_name = "contacts"
    template_name = 'contacts/index.html'
    paginate_by = 20


class ContactDetailView(DetailView):
    model = PersonContact
    context_object_name = "contact"
    template_name = "contacts/deatail.html"

class ContactCreateView(CreateView):
    model = PersonContact
    template_name = 'contacts/form.html'
    fields = '__all__'

class ContactUpdateView(UpdateView):
    model = PersonContact
    template_name = 'contacts/form.html'
    fields = '__all__'


class ContactDeleteView(DeleteView):
    model = PersonContact
    context_object_name = "contact"
    template_name = 'contacts/delete.html'
    success_url = reverse_lazy('contacts:index')

contacts/templates/contacts/base.html
{% load static  %}

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" type="text/css" href="{% static 'contacts/materialize.css' %}">
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   <title>Document</title>
</head>
<body>
    <nav class="light-blue darken-4">
        <div class="nav-wrapper">
          <a href="{% url 'contacts:index' %}" class="brand-logo right"><i class="medium material-icons">book</i></a>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><a href="{% url 'contacts:index' %}">Home</a></li>
            <li><a href="{% url 'contacts:create' %}">Add Contact</a></li>
            <li><a href="collapsible.html">JavaScript</a></li>
          </ul>
        </div>
      </nav>

      <div class="container">
        {% block content %}{% endblock content %}
      </div>

      <footer class="page-footer light-blue darken-4 m-3" style="margin-top:15px;">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Footer Content</h5>
              <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="white-text">Links</h5>
              <ul>
                <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container">
          © 2014 Copyright Text
          <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
          </div>
        </div>
      </footer>
      
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

contacts/templates/contacts/deatail.html
{% extends "contacts/base.html" %}

{% block content %}
<div class="center-align" style="padding:20px; margin-bottom: 150px;">
    <div class="col s12 m6">
      <div class="card blue darken-1">
        <div class="card-content white-text">
          <h3 class="card-title">{{ contact.first_name }} {{ contact.last_name }}</h3>
          <p>Phone Number: {{contact.phone_number}}</p>
          <p>Email: {{contact.email}}</p>
          <p>Date Of Birth: {{contact.date_of_birth}}</p>
        </div>
        <div class="card-action">
          <a href="{% url "contacts:contact-update" contact.id %}" class="btn blue">Update<i class="material-icons left">create</i></a>
          <a href="{% url "contacts:contact-delete" contact.id %}" class="btn red">Delete<i class="material-icons left">delete</i></a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

contacts/templates/contacts/delete.html
{% extends "contacts/base.html" %}

{% block content %}
    <form class="col s12" action="" method="POST">
        {% csrf_token %}
        
            
        <p>Are you sure you want to delete "{{ contact }}"?</p>
        <button class="btn blue" type="submit">Confirm</button>
        <a href="{% url "contacts:contact" object.id %}" class="btn grey" type="submit">Cancel</a>
    </form>
{% endblock content %}

contacts/templates/contacts/form.html
{% extends "contacts/base.html" %}

{% block content %}
    <form class="col s12" action="" method="POST">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {# Include the visible fields #}
        {% for field in form.visible_fields %}
            <div class="row">
                <div class="input-field col s12">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
        </div>
        {% endfor %}
        <button class="btn blue" type="submit">Submit</button>
    </form>
{% endblock content %}

contacts/templates/contacts/index.html
{% extends "contacts/base.html" %}

{% block content %}
<h3 class="light-blue-text darken-4 center-align">CONTACTS</h3>
<div class="collection">
    {% for contact in contacts %}
    <a href="{% url 'contacts:contact' contact.id %}" class="collection-item light-blue-text darken-4">{{ contact.first_name }} {{ contact.last_name }}
        
    </a>
    {% endfor %}
   
  </div>
            
  {% if is_paginated %}

        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

    
{% endblock content %}